### ISSUE TITLE
Exporter has broken with key --database=_all_dbs

### ISSUE THREAD

**Issue by DmitroDemchenko** [gesellix/couchdb-prometheus-exporter#173]
Hello! Exported has stopped work with key --database=_all_dbs.
When I've run:
```/usr/local/bin/couchdb-prometheus-exporter --couchdb.uri=http://127.0.0.1:5984 --couchdb.username=${user} --couchdb.password={password}--databases= --telemetry.address {addr}:9984```

My process is running. And after first curl request I have an error:
 
```
panic: interface conversion: interface {} is int32, not uint8

goroutine 24 [running]:
github.com/gesellix/couchdb-prometheus-exporter/lib.convertSeq(0x96a180, 0xc00042af80, 0xc00040b560)
	/root/go/pkg/mod/github.com/gesellix/couchdb-prometheus-exporter@v0.0.0-20200724221344-2bdacc53e2d1/lib/couch-util.go:51 +0x1eb
github.com/gesellix/couchdb-prometheus-exporter/lib.convert(0x9a6d20, 0xc00042b260, 0x8d, 0x9a6d20, 0xc00042b260)
	/root/go/pkg/mod/github.com/gesellix/couchdb-prometheus-exporter@v0.0.0-20200724221344-2bdacc53e2d1/lib/couch-util.go:69 +0x19e
github.com/gesellix/couchdb-prometheus-exporter/lib.DecodeUpdateSeq(0xc0001880d0, 0xc1, 0xc0001b41a0, 0x1a, 0xc0000d5ff8, 0xc0004500c0, 0xa)
	/root/go/pkg/mod/github.com/gesellix/couchdb-prometheus-exporter@v0.0.0-20200724221344-2bdacc53e2d1/lib/couch-util.go:104 +0x4c5
github.com/gesellix/couchdb-prometheus-exporter/lib.(*Exporter).collectV2(0xc000190780, 0xc0001b3770, 0xf, 0xc0001b3b90, 0xeebc68, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/gesellix/couchdb-prometheus-exporter@v0.0.0-20200724221344-2bdacc53e2d1/lib/collector-v2.go:118 +0x33d8
github.com/gesellix/couchdb-prometheus-exporter/lib.(*Exporter).collect(0xc000190780, 0xc000148180, 0x0, 0x0)
	/root/go/pkg/mod/github.com/gesellix/couchdb-prometheus-exporter@v0.0.0-20200724221344-2bdacc53e2d1/lib/collector.go:298 +0xf7f
github.com/gesellix/couchdb-prometheus-exporter/lib.(*Exporter).Collect(0xc000190780, 0xc000148180)
	/root/go/pkg/mod/github.com/gesellix/couchdb-prometheus-exporter@v0.0.0-20200724221344-2bdacc53e2d1/lib/collector.go:391 +0x9d
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
	/root/go/pkg/mod/github.com/prometheus/client_golang@v1.7.1/prometheus/registry.go:444 +0x19d
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/root/go/pkg/mod/github.com/prometheus/client_golang@v1.7.1/prometheus/registry.go:536 +0xe12

```

If I don't use key --database=_all_dbs my curl request return metrics, but in this case I don't have any metrics about DBs.
Can someone help with it ?

**Comment by DmitroDemchenko** [comment]
There is any limits on documents per DB?  I found, seems I have this issue with DB that have  38339 documents.
If I try use another per DB requests where there are not a lot docs. My request work.

**Comment by gesellix** [comment]
Can you check which version of the exporter you're currently using? I think that the error should already been fixed with #112, which has been released with [v30.1.0](https://github.com/gesellix/couchdb-prometheus-exporter/releases/tag/v30.1.0).

**Comment by DmitroDemchenko** [comment]
I see this message:
``` couchdb-prometheus-exporter --version
CouchDB Prometheus Exporter version dev (none, unknown)```

Can you please tell me how can I update it ?

**Comment by gesellix** [comment]
I suppose that you built the exporter manually from sources. Since I don't know how you downloaded the sources, I'll give you a list with several options, hoping that one of them fits for your situation :)

- manually download the current sources (not an official release) as .zip file: https://github.com/gesellix/couchdb-prometheus-exporter/archive/refs/heads/master.zip
- clone the repository with Git: `git clone https://github.com/gesellix/couchdb-prometheus-exporter.git` or `git clone git@github.com:gesellix/couchdb-prometheus-exporter.git`
- if you already cloned the repository using Git, then a `git pull` should update everything
- download a binary for your platform from the releases page: https://github.com/gesellix/couchdb-prometheus-exporter/releases (most recent version is [v30.3.0](https://github.com/gesellix/couchdb-prometheus-exporter/releases/tag/v30.3.0))
- run the eporter as Docker container: see the readme at https://github.com/gesellix/couchdb-prometheus-exporter#run-it-as-container, e.g. like below:
    ```
    docker run --rm gesellix/couchdb-prometheus-exporter:v30.3.0 --version          
    CouchDB Prometheus Exporter version dev (none, 2022-09-17T19:07:51Z)
    ```

When running the exporter from the sources (by download or Git) you won't get a real version (only `dev (none, unknown)`). When downloading a proper release, the version should look like this: `CouchDB Prometheus Exporter version 30.3.0 (42e60d8, 2022-09-17T21:07:13+02:00)`... the Docker container doesn't print such a helpful version, but the Docker image itself is selected by the released version.

Please leave a comment if that helped!

**Comment by DmitroDemchenko** [comment]
I've installed like in github instruction: 
```export GO111MODULE=on  # in a Windows shell, please replace `export` with `set`
go get github.com/gesellix/couchdb-prometheus-exporter
```
Now I've updated go to 1.19 and tried like you mentioned. But result the same :(

**Comment by gesellix** [comment]
Oh, great, looks like I forgot to update the README....

Can you try this one? That would be the modern approach of installing a Golang module:

```
# optional, should not be relevant for Golang 1.19
unset GO111MODULE

# install from the latest release
go install github.com/gesellix/couchdb-prometheus-exporter/v30@v30.3.0
```

**Comment by DmitroDemchenko** [comment]
Working! thanks

**Comment by gesellix** [comment]
Great! I'll keep this issue open as reminder for myself to update the readme.
