### ISSUE TITLE
getting "cannot create log" error and container not starting up

### ISSUE THREAD

**Issue by devopscloudnexus** [gesellix/couchdb-prometheus-exporter#25]
I am trying to start the container using the example command but I am getting an error.
```
$ docker run -p 9984:9984 gesellix/couchdb-prometheus-exporter -couchdb.uri=http://10.2.1.8:1212
$ docker logs dd913dfbc8b4
I0528 18:35:48.966073       1 couchdb-exporter.go:77] Starting exporter at '0.0.0.0:9984' to read from CouchDB at 'http://10.2.1.8:1212'
log: exiting because of error: log: cannot create log: open /tmp/couchdb-prometheus-exporter.dd913dfbc8b4.unknownuser.log.INFO.20180528-183548.1: no such file or directory
```
Why is this happening and how can I provide more information to help this debug?

**Comment by gesellix** [comment]
Thank you for hinting me at the wrong docs! The documented example doesn't work, because meanwhile the container has been cleaned up so that the `/tmp` directory doesn't exist anymore, which makes the logging library fail to write into `/tmp`.
You have to decide yourself how you'd like to handle logs and you have the following options:

1) don't write logs to `/tmp`, but to stderr:

```
docker run -p 9984:9984 gesellix/couchdb-prometheus-exporter -couchdb.uri=http://10.2.1.8:1212 -logtostderr
```

2) provide a `/tmp` directory inside the container (using a volume):

```
docker run -p 9984:9984 -v `pwd`/tmp:/tmp gesellix/couchdb-prometheus-exporter -couchdb.uri=http://10.2.1.8:1212
```

I'm going to update the README.

**Comment by gesellix** [comment]
@devopscloudnexus I hope the examples made it work for you. I've updated the README.
