### ISSUE TITLE
Cannot see any metrics related to the couch

### ISSUE THREAD

**Issue by hamedminaee** [gesellix/couchdb-prometheus-exporter#55]
Hi,

I am trying to usecouchdb-prometheus-exporter so here is what I did:

`docker run -p 9984:9984 gesellix/couchdb-prometheus-exporter --couchdb.uri=http://couchdb:5984 --databases=test_jmeter_test_db_size_80_k --couchdb.username=root --couchdb.password=a-secret
`
and I see the following:

`docker run -p 9984:9984 gesellix/couchdb-prometheus-exporter --couchdb.uri=http://xxxxxxxxx.nip.io:80 --databases=test_jmeter_test_db_size_80_k --couchdb.username=admin --couchdb.password=xxxxxxx`

However when I check the prometheus metrics I cannot see any metrics related to couch? Am I missing any step?

![image](https://user-images.githubusercontent.com/52859974/65365738-45bb9280-dbf2-11e9-945d-3627329234f5.png)

**Comment by gesellix** [comment]
Hi,

did you also add the relevant Prometheus config, so that Prometheus collects the exporter's metrics?
It should look like the example at https://github.com/gesellix/couchdb-prometheus-exporter/blob/51e363bac1d76c99bdb8cdcef3e5c720c8db59c5/examples/grafana/prometheus/prometheus.yml#L49.

**Comment by hamedminaee** [comment]
@gesellix Thanks gesellix,

I use Openshift and I can see prometheus is there because I see this:

![image](https://user-images.githubusercontent.com/52859974/65381042-add7aa80-dcbe-11e9-9d2f-3f9f17687474.png)

Also as the following link suggest:

https://docs.openshift.com/container-platform/3.11/install_config/prometheus_cluster_monitoring.html

The following command is the only one I see which I can edit config files:

`oc -n openshift-monitoring edit configmap cluster-monitoring-config`

But this is not similar to what you mentioned.
Can you explain more on where I can find  prometheus.yml?

**Comment by gesellix** [comment]
I've no experience with OpenShift, so I can only guess reading the docs. This paragraph seems to be the relevant bit:

> The Prometheus Operator (PO) creates, configures, and manages Prometheus and Alertmanager instances. It also automatically generates monitoring target configurations based on familiar Kubernetes label queries.

Based on that paragraph, without having any idea if that's "the correct way to go": you should probably add labels on your CouchDB-Exporter instance, so that OpenShift's Prometheus Operator finds the exporter.

I have no idea which labels those should be and how they are named. As I said: I have no experience with OpenShift.

**Comment by hamedminaee** [comment]
Just to double check,

By CouchDB-Exporter instance 

> add labels on your CouchDB-Exporter instance

 you mean customizing this repo : gesellix/couchdb-prometheus-exporter. Right?

**Comment by gesellix** [comment]
Yes, you're right, I meant that you'll need to configure Prometheus to scrape the gesellix/couchdb-prometheus-exporter instance at port 9984, so that it appears on the console like the other entries (node-exporter, prometheus-k8s, prometheus-operator).

Regarding the ip address: I would expect that some part of OpenShift or Kubernetes solves that for you, which is why you'll need to add labels on your container. That also implies that the instance on port 9984 needs to be in the same network (say: it needs to be reachable und be discovered).

_How_ you solve that in your setup is out of my knowledge. Maybe reading about the technical options on how you add labels in different setups might give you a clue or help you finding a good example. So I'll note different links to the same topic "adding labels" here:
- [Adding Labels on a plain Docker container](https://docs.docker.com/engine/reference/commandline/run/#set-metadata-on-container--l---label---label-file)
- [Adding labels on a Docker service (think: Docker Swarm)](https://docs.docker.com/engine/reference/commandline/service_create/#set-metadata-on-a-service--l---label)
- [Adding labels on a Kubernetes Object](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/)
- [Managing labels in OpenShift pods and services](https://docs.openshift.com/online/architecture/core_concepts/pods_and_services.html#labels)

I really hope that helps somehow. Please feel free to keep me updated here, so that we might add some hints about OpenShift in the Readme or in the examples. I'm keen to learn how this issue can be solved!

**Comment by gesellix** [comment]
... not sure if this one helps: https://github.com/openshift/cluster-monitoring-operator/issues/156#issuecomment-439902982

- Labels need to be declared
- Namespace needs to match
- Prometheus serviceaccount needs to have permission to access the namespace

**Comment by gesellix** [comment]
Hi @hamedminaee, did you have any progress?

**Comment by hamedminaee** [comment]
@gesellix  Thanks for the follow up 
No not much progress yet

**Comment by pankaj-dahiya** [comment]
Hi I am not getting the stated metrics in readme_metrics. Metrics I got are below:

# HELP couchdb_httpd_up Was the last query of CouchDB stats successful.
# TYPE couchdb_httpd_up gauge
couchdb_httpd_up 0
# HELP go_gc_duration_seconds A summary of the GC invocation durations.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 8.39e-06
go_gc_duration_seconds{quantile="0.25"} 1.3744e-05
go_gc_duration_seconds{quantile="0.5"} 4.3167e-05
go_gc_duration_seconds{quantile="0.75"} 7.3545e-05
go_gc_duration_seconds{quantile="1"} 0.009976623
go_gc_duration_seconds_sum 0.925326122
go_gc_duration_seconds_count 4601
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 9
# HELP go_info Information about the Go environment.
# TYPE go_info gauge
go_info{version="go1.12.12"} 1
# HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
# TYPE go_memstats_alloc_bytes gauge
go_memstats_alloc_bytes 1.506624e+06
# HELP go_memstats_alloc_bytes_total Total number of bytes allocated, even if freed.
# TYPE go_memstats_alloc_bytes_total counter
go_memstats_alloc_bytes_total 1.4705102888e+10
# HELP go_memstats_buck_hash_sys_bytes Number of bytes used by the profiling bucket hash table.
# TYPE go_memstats_buck_hash_sys_bytes gauge
go_memstats_buck_hash_sys_bytes 1.537791e+06
# HELP go_memstats_frees_total Total number of frees.
# TYPE go_memstats_frees_total counter
go_memstats_frees_total 2.3518451e+07
# HELP go_memstats_gc_cpu_fraction The fraction of this program's available CPU time used by the GC since the program started.
# TYPE go_memstats_gc_cpu_fraction gauge
go_memstats_gc_cpu_fraction 5.213479134022664e-06
# HELP go_memstats_gc_sys_bytes Number of bytes used for garbage collection system metadata.
# TYPE go_memstats_gc_sys_bytes gauge
go_memstats_gc_sys_bytes 2.377728e+06
# HELP go_memstats_heap_alloc_bytes Number of heap bytes allocated and still in use.
# TYPE go_memstats_heap_alloc_bytes gauge
go_memstats_heap_alloc_bytes 1.506624e+06
# HELP go_memstats_heap_idle_bytes Number of heap bytes waiting to be used.
# TYPE go_memstats_heap_idle_bytes gauge
go_memstats_heap_idle_bytes 6.3578112e+07
# HELP go_memstats_heap_inuse_bytes Number of heap bytes that are in use.
# TYPE go_memstats_heap_inuse_bytes gauge
go_memstats_heap_inuse_bytes 2.777088e+06
# HELP go_memstats_heap_objects Number of allocated objects.
# TYPE go_memstats_heap_objects gauge
go_memstats_heap_objects 3127
# HELP go_memstats_heap_released_bytes Number of heap bytes released to OS.
# TYPE go_memstats_heap_released_bytes gauge
go_memstats_heap_released_bytes 6.0366848e+07
# HELP go_memstats_heap_sys_bytes Number of heap bytes obtained from system.
# TYPE go_memstats_heap_sys_bytes gauge
go_memstats_heap_sys_bytes 6.63552e+07
# HELP go_memstats_last_gc_time_seconds Number of seconds since 1970 of last garbage collection.
# TYPE go_memstats_last_gc_time_seconds gauge
go_memstats_last_gc_time_seconds 1.5873941429252028e+09
# HELP go_memstats_lookups_total Total number of pointer lookups.
# TYPE go_memstats_lookups_total counter
go_memstats_lookups_total 0
# HELP go_memstats_mallocs_total Total number of mallocs.
# TYPE go_memstats_mallocs_total counter
go_memstats_mallocs_total 2.3521578e+07
# HELP go_memstats_mcache_inuse_bytes Number of bytes in use by mcache structures.
# TYPE go_memstats_mcache_inuse_bytes gauge
go_memstats_mcache_inuse_bytes 6944
# HELP go_memstats_mcache_sys_bytes Number of bytes used for mcache structures obtained from system.
# TYPE go_memstats_mcache_sys_bytes gauge
go_memstats_mcache_sys_bytes 16384
# HELP go_memstats_mspan_inuse_bytes Number of bytes in use by mspan structures.
# TYPE go_memstats_mspan_inuse_bytes gauge
go_memstats_mspan_inuse_bytes 35424
# HELP go_memstats_mspan_sys_bytes Number of bytes used for mspan structures obtained from system.
# TYPE go_memstats_mspan_sys_bytes gauge
go_memstats_mspan_sys_bytes 49152
# HELP go_memstats_next_gc_bytes Number of heap bytes when next garbage collection will take place.
# TYPE go_memstats_next_gc_bytes gauge
go_memstats_next_gc_bytes 4.194304e+06
# HELP go_memstats_other_sys_bytes Number of bytes used for other system allocations.
# TYPE go_memstats_other_sys_bytes gauge
go_memstats_other_sys_bytes 1.196537e+06
# HELP go_memstats_stack_inuse_bytes Number of bytes in use by the stack allocator.
# TYPE go_memstats_stack_inuse_bytes gauge
go_memstats_stack_inuse_bytes 753664
# HELP go_memstats_stack_sys_bytes Number of bytes obtained from system for stack allocator.
# TYPE go_memstats_stack_sys_bytes gauge
go_memstats_stack_sys_bytes 753664
# HELP go_memstats_sys_bytes Number of bytes obtained from system.
# TYPE go_memstats_sys_bytes gauge
go_memstats_sys_bytes 7.2286456e+07
# HELP go_threads Number of OS threads created.
# TYPE go_threads gauge
go_threads 11
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 104.59
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1.048576e+06
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 8
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 1.8378752e+07
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.58704181019e+09
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 1.18898688e+08
# HELP process_virtual_memory_max_bytes Maximum amount of virtual memory available in bytes.
# TYPE process_virtual_memory_max_bytes gauge
process_virtual_memory_max_bytes -1
# HELP promhttp_metric_handler_requests_in_flight Current number of scrapes being served.
# TYPE promhttp_metric_handler_requests_in_flight gauge
promhttp_metric_handler_requests_in_flight 1
# HELP promhttp_metric_handler_requests_total Total number of scrapes by HTTP status code.
# TYPE promhttp_metric_handler_requests_total counter
promhttp_metric_handler_requests_total{code="200"} 23490
promhttp_metric_handler_requests_total{code="500"} 0
promhttp_metric_handler_requests_total{code="503"} 0

**Comment by gesellix** [comment]
@pankaj-dahiya since I'm not sure if your issue is related to hamedminaee's one, please open a [new issue](https://github.com/gesellix/couchdb-prometheus-exporter/issues/new/choose) where we can go into detail.
While doing so, please try to apply some basic formatting for the list of metrics, you might for example wrap them in backticks to format them as code to make them more readable:

    ````
     <content goes here...>
    ````

Thanks!

**Comment by gesellix** [comment]
Closing - feel free to comment or reopen if you have any updates regarding the interoperability with Openshift.
