### ISSUE TITLE
urlencode db names

### ISSUE THREAD

**Issue by IndeedNotJames** [gesellix/couchdb-prometheus-exporter#63]
Hi! :)
I have multiple dbs containing a `/` in the db name. That's why I can't use `--databases _all_dbs`.

#### Example (db name: `something/test`):
 
This exporter tries to `GET /something/test`, which leads to a #404, because it's not urlencoded. The correct request would be `GET /something%2Ftest`.

There is no problem with the db itself. Adding `something%2Ftest` to `$DATABASES`/`--databases` works as intended.

Would be awesome if you could fix that, so I can actually use this exporter without adding every single db myself manually :)

**Comment by gesellix** [comment]
Hey, thanks for your issue!

It has been fixed with release v27.1.0, which is available at https://github.com/gesellix/couchdb-prometheus-exporter/releases. The Docker image will be available at https://hub.docker.com/r/gesellix/couchdb-prometheus-exporter/tags?page=1&name=v27.1.0 as soon as the automated build has been finished.

**Comment by IndeedNotJames** [comment]
Awesome :rocket: 

Thank you very much :)

**Comment by gesellix** [comment]
A little update: v27.1.0 had another issue regarding the Docker Build, the fix is available with https://hub.docker.com/r/gesellix/couchdb-prometheus-exporter/tags?page=1&name=v27.1.1
